### ISSUE TITLE
Random jump back to account location

### ISSUE THREAD

**Issue by huan7300** [iam4x/pokemongo-webspoof#203]
In the middle of game, whether it be catching a pokemon or look at a gym, it will random put me back at my original location (my actual GPS location)

**Comment by soroshd** [comment]
I get this sometimes too. Even when I spoof my location before opening the app. I first control if Google Maps is showing the location I have chosen and then I open the app. But whatever I do, it always shows me first my own location and than jumps to the locatie I have chosen.

**Comment by kurosyke** [comment]
I have the same problem and I keep getting softbanned because of it.

**Comment by tonynkh** [comment]
Same here

**Comment by seffignoz** [comment]
same.

**Comment by maegen** [comment]
Same just now.

**Comment by herocertified** [comment]
#121

**Comment by z06jaz** [comment]
when it teleports you back to your location, even if its for a split second, exit pokemon go game app immiditely  on your phone and start it again. This prevents you from being soft banned.

**Comment by leonfrischauf** [comment]
Is there a fix that is working for this error? Will there be a fix in 1.2?

**Comment by kurosyke** [comment]
@leonfrischauf I had to make the account in device management trusted before starting the app, that fixed it for me atleast. Basically restart everything from scratch and try to hit trust before the app starts.

**Comment by leonfrischauf** [comment]
@kurosyke Thank you for your answer!
Only one question: What do you mean to restart everything from scratch. Also when I first start the app, Xcode tells me it would not be possible as the certificate is not trusted. Then I go to settings and trust the certificate and rerun the Xcode build. Is this false?

**Comment by kurosyke** [comment]
@leonfrischauf Just reset everything, delete the app etc. and fully reinstall, rerun... To answer your second question, that's normal. But if I don't want to be teleported back to my real location you have to trust the account in device managment before it can try to run it on your iPhone. If you get the error that you have to trust it in device managment it won't work fine, atleast from what I have experienced.
I hope you understand what I mean, English is not my first language.

**Comment by leonfrischauf** [comment]
Thank you again for your answer. I will try it tomorrow. This is also possible with a free developer account, isn't it? @kurosyke

**Comment by kurosyke** [comment]
@leonfrischauf No problem. Yes, it is.

**Comment by iam4x** [comment]
This should be fixed with v1.2.0, if it's stills happen is that pokemongo is using too much memory from your iOS device. Restart it 👍

**Comment by Takage** [comment]
Not fixed!
Just tested with the new version. While it is definitly more stable it just hoped around again.

**Comment by Takage** [comment]
Edit: Just happened again. I did restart my iPhone. It should have enough memory. Xcode ist still running when it is jumping.

**Comment by a7medo778** [comment]
problem still exist in the new release
i am getting thrown out of gym battles because of it...

**Comment by IPyandy** [comment]
confirmed, this still happens, though less often.. phone restarted, ipad restarted. seems to happen more often with auto-pilot used, less often when manually moving around.

**Comment by lyyvalhalla** [comment]
found this happens whenever the server status changes.

**Comment by huan7300** [comment]
I find that when I get the memory warning on xCode, it's when I find my phone gets really hot. Once my phone gets really warm, the spoofer will stop running, and it'll send me back to my original location. If I build and run the spoofer again, within minutes it'll kick me back to my original location. This happens especially fast when I do gym battles, so I've been avoiding them. I was able to play for about 3 hours before I got returned to my original location. I'm assuming after the first kick, it's best to wait for about an hour for the phone to cool down. These are just my speculations. Although the webspoof v1.2 is much better than the previous version, and does not happen as fast or often. Thanks for the update! (:

**Comment by brnmckllr** [comment]
Still jumping for me too on v1.2.0. I deleted everything and am going to go at it again tomorrow.

**Comment by brnmckllr** [comment]
scratch that, it glitches more when you use the auto move feature, if you go manually, doesn't seem to end in a soft ban, even when it glitches.  But I also wasn't going that far away from my house.

**Comment by joshpalan** [comment]
Has anyone been able to start from your spoofed location? When I open pokemon go, even after setting the spoof app up and setting everything, I still start from my actual location before immediately jumping to the spoofed location. I don't really have this issue while the app is running unless it crashes, and I haven't seen it happening during autopilot either.
