### ISSUE TITLE
Error autoclick Xcode - code 2

### ISSUE THREAD

**Issue by MrMillionDollarSmile** [iam4x/pokemongo-webspoof#68]
Whenever I try to move this error pops up

/Contents/Resorces/app/autoclick.applescript execution error: System Events got an error: Can't get menu bar 1 of process "Xcode". Invalid index. (-1719)

Also, if it helps, my Xcode shows an error that says there's No provisional profiles found

**Comment by bello356** [comment]
I have the same issue

**Comment by AbelIngrand** [comment]
Does the blank app launch on your phone ?

**Comment by AbelIngrand** [comment]
Try this fix This issue as already been addressed here https://github.com/iam4x/pokemongo-webspoof/issues/5#issuecomment-233124626

**Comment by bello356** [comment]
The main issue I have with mine is this:

https://github.com/iam4x/pokemongo-webspoof/issues/69

Made a post about it earlier but still no luck

**Comment by iam4x** [comment]
Duplicated of #5, try theses steps also: https://github.com/iam4x/pokemongo-webspoof/issues/28#issuecomment-233265874

**Comment by molonlabe88** [comment]
Damn its annoying how iam4x closed these though they don't fix it.
